version: '2'

networks:
  blockchain:

services:
  ca.entity1.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.entity1.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.entity1.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca2fc03f96a58f747e6357805e6db3077d69e9beb74ea73ea71e2cd151a23b97_sk
    ports:
      - 8054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/entity1.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.entity1.com
    networks:
      - blockchain

  peer0.entity1.com:
    container_name: peer0.entity1.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.entity1.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Entity1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.entity1.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_blockchain
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=state.entity1.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/entity1.com/peers/peer0.entity1.com/msp/:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/entity1.com/users/:/etc/hyperledger/msp/users
        - ./config/:/etc/hyperledger/configtx
    depends_on:
      - state.entity1.com
    networks:
      - blockchain

  state.entity1.com:
    container_name: state.entity1.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 8984:5984
    networks:
      - blockchain

