version: '2'

networks:
  blockchain:

services:
  ca.entity2.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.entity2.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.entity2.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/de5eb5a1dda900c936c134093094cd817fc919df6507ccfe5845670d7d8d1db3_sk
    ports:
      - 9054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/entity2.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.entity2.com
    networks:
      - blockchain

  peer0.entity2.com:
    container_name: peer0.entity2.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.entity2.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_LOCALMSPID=Entity2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.entity2.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_blockchain
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=state.entity2.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/entity2.com/peers/peer0.entity2.com/msp/:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/entity2.com/users/:/etc/hyperledger/msp/users
        - ./config/:/etc/hyperledger/configtx
    depends_on:
      - state.entity2.com
    networks:
      - blockchain

  state.entity2.com:
    container_name: state.entity2.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 9984:5984
    networks:
      - blockchain
